version: '3'
services:
  alpine:
    build: .
    image: 'goex'
    ports:
      - '8080:8080'
    depends_on:
      - elastic
    networks:
      - front
    restart: on-failure

  elastic:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.4'
    ports:
      - '9200:9200'
    networks:
      - front

networks:
  front:
    driver: bridge



